pool:
  name: 'rollout'

stages:
- stage: BuildDockerImage
  displayName: 'Build Docker Image'
  jobs:
  - job: build
    displayName: 'Build Docker Image'
    steps:
    - checkout: self

    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        containerRegistry: 'perseverance01'
        repository: 'perseverance-project'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          backend_$(Build.BuildId)
      name: buildImage

- stage: PushDockerImage
  displayName: 'Push Docker Image'
  dependsOn: BuildDockerImage
  jobs:
  - job: push
    displayName: 'Push Docker Image to ACR'
    steps:
    - task: Docker@2
      displayName: 'Push Docker Image'
      inputs:
        containerRegistry: 'perseverance01'
        repository: 'perseverance-project'
        command: 'push'
        tags: |
          backend_$(Build.BuildId)
